export const SEC = 1
export const SEC_MS = 1000
export const MIN_S = 60
export const MIN_MS = 60 * SEC_MS
export const HOUR_S = 60 * MIN_S
export const HOUR_MS = 60 * MIN_MS
export const DAY_S = 24 * HOUR_S
export const DAY_MS = 24 * HOUR_MS
export const WEEK_S = 7 * DAY_S
export const WEEK_MS = 7 * DAY_MS
export const MONTH_S = 30 * DAY_S
export const MONTH_MS = 30 * DAY_MS
export const YEAR_S = 365 * DAY_S
export const YEAR_MS = 365 * DAY_MS
